//main input
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_EDITED_SEARCH_TERM = 'SET_EDITED_SEARCH_TERM';
//favourite request
export const SET_FAV_REQUEST = 'SET_FAV_REQUEST';
export const SET_EDITED_FAV_REQUEST = 'SET_EDITED_FAV_REQUEST'; 
//Requested videos
export const SET_REQUESTED_VIDEOS= 'SET_REQUESTED_VIDEOS';
// // Favourites
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const DELETE_FAV_REQUEST = 'DELETE_FAV_REQUEST';
export const ACTIVE_FAV_REQUEST = 'ACTIVE_FAV_REQUEST';
export const SAVE_EDITED_FAV_REQUEST = 'SAVE_EDITED_FAV_REQUEST'
// Modal window
export const SET_IS_MODAL_OPEN = 'SET_IS_MODAL_OPEN';
export const SET_IS_EDIT_MODAL_OPEN = 'SET_IS_EDIT_MODAL_OPEN';